name: UltraTitle
version: 1.0
main: me.ryandw11.ultratitle.core.Main
author: ryandw11
description: This is a Title Plugin!
commands:
    title:
     description: Main Command for UltraTitle!
     aliases: [t, utitle, ut]